// Automatically generated by the res2go IDE plug-in, do not edit.
package main

import (
	"github.com/ying32/govcl/vcl"
	"github.com/ying32/govcl/vcl/types"
)

type TMainForm struct {
	*vcl.TForm
	PageControl            *vcl.TPageControl
	PageScan               *vcl.TTabSheet
	ListView               *vcl.TListView
	PageEditPic            *vcl.TTabSheet
	PageRework             *vcl.TTabSheet
	StatusBar              *vcl.TStatusBar
	SelectDirectoryDialog1 *vcl.TSelectDirectoryDialog
}

var MainForm *TMainForm

// func NewMainForm(owner vcl.IComponent) (root *TMainForm) {
// 	vcl.CreateResForm(owner, &root)
// 	return
// }

func (f *TMainForm) OnFormCreate(sender vcl.IObject) {
	// 主窗口
	f.SetCaption("时源科技")
	constraints := f.Constraints()
	constraints.SetMinHeight(600)
	constraints.SetMinWidth(860)
	f.SetConstraints(constraints)
	f.SetHeight(600)
	f.SetPosition(types.PoDesktopCenter)
	f.SetWidth(860)

	// 状态栏
	f.StatusBar = vcl.NewStatusBar(f)
	f.StatusBar.SetParent(f)
	f.StatusBar.SetAnchors(types.NewSet( // 设置锚点
		types.AkBottom, types.AkLeft, types.AkRight, types.AkTop))
	f.StatusBar.SetHeight(22)
	f.StatusBar.SetTop(578)
	f.StatusBar.SetWidth(860)
	f.StatusBar.SetSimpleText("hello")

	// 标签页面控制器
	f.PageControl = vcl.NewPageControl(f)
	f.PageControl.SetParent(f)
	f.PageControl.SetActivePageIndex(0)
	f.PageControl.SetAnchors(types.NewSet( // 设置锚点
		types.AkBottom, types.AkLeft, types.AkRight, types.AkTop))
	f.PageControl.SetHeight(574)
	f.PageControl.SetWidth(860)

	// 扫描页面
	f.PageScan = vcl.NewTabSheet(f)
	f.PageScan.SetParent(f.PageControl)
	f.PageScan.SetCaption("扫描")
	f.PageScan.SetHeight(544)
	f.PageScan.SetWidth(852)

	// 修图页面
	f.PageEditPic = vcl.NewTabSheet(f)
	f.PageEditPic.SetParent(f.PageControl)
	f.PageEditPic.SetCaption("修图")
	f.PageEditPic.SetHeight(544)
	f.PageEditPic.SetWidth(852)

	// 返工页面
	f.PageRework = vcl.NewTabSheet(f)
	f.PageRework.SetParent(f.PageControl)
	f.PageRework.SetCaption("返工")
	f.PageRework.SetHeight(544)
	f.PageRework.SetWidth(852)

	// 列表
	f.ListView = vcl.NewListView(f)
	f.ListView.SetParent(f.PageScan)
	f.ListView.SetAnchors(types.NewSet( // 设置锚点
		types.AkBottom, types.AkLeft, types.AkRight, types.AkTop))
	columns := vcl.NewListColumns(f.ListView)
	column0 := columns.Add()
	column0.SetCaption("序号")
	column0.SetWidth(48)
	column1 := columns.Add()
	column1.SetCaption("档号")
	column1.SetWidth(695)
	column2 := columns.Add()
	column2.SetCaption("文件数")
	column2.SetWidth(100)
	f.ListView.SetColumns(columns)
	f.ListView.SetGridLines(true)
	f.ListView.SetHeight(456)
	f.ListView.SetReadOnly(true)
	f.ListView.SetRowSelect(true)
	f.ListView.SetTop(88)
	f.ListView.SetViewStyle(types.VsReport)
	f.ListView.SetWidth(848)
}
